version: '3'

services:
  selenium:
    image: selenium/standalone-chromium:130.0-chromedriver-130.0  
    container_name: selenium
    ports:
      - "4444:4444"  
    networks:
      - selenium_network  

  app:
    build:
      context: .  
      dockerfile: Dockerfile 
    container_name: app_mkretv
    depends_on:
      - selenium 
    networks:
      - selenium_network  
    secrets:
      - firestore_secret  

networks:
  selenium_network:
    driver: bridge  

secrets:
  firestore_secret:
    external: true  


